make MessageDialogFragment public static class
because if it is anonymous class, we get
IllegalStateException: Fragment null must be a public static class to be
properly recreated from instance state